/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package milvus2

import (
	"github.com/milvus-io/milvus/client/v2/entity"
)

// ConsistencyLevel represents the consistency level for Milvus operations.
type ConsistencyLevel int

const (
	// ConsistencyLevelDefault lets Milvus use its built-in default consistency level.
	// When creating a collection, if this is set (zero value), no explicit consistency
	// level is passed, and Milvus defaults to Bounded Staleness.
	ConsistencyLevelDefault ConsistencyLevel = iota
	// ConsistencyLevelStrong guarantees that reads return the most recent data.
	ConsistencyLevelStrong
	// ConsistencyLevelSession ensures read-your-write consistency within the same session.
	ConsistencyLevelSession
	// ConsistencyLevelBounded allows reads to return data within a certain staleness bound.
	ConsistencyLevelBounded
	// ConsistencyLevelEventually provides eventual consistency with no staleness guarantees.
	ConsistencyLevelEventually
	// ConsistencyLevelCustomized allows custom consistency configuration.
	ConsistencyLevelCustomized
)

// ToEntity converts ConsistencyLevel to the Milvus SDK entity.ConsistencyLevel type.
// Note: ConsistencyLevelDefault should be checked before calling this method,
// as it indicates "use default" and should be resolved first.
func (c ConsistencyLevel) ToEntity() entity.ConsistencyLevel {
	switch c {
	case ConsistencyLevelStrong:
		return entity.ClStrong
	case ConsistencyLevelSession:
		return entity.ClSession
	case ConsistencyLevelBounded:
		return entity.ClBounded
	case ConsistencyLevelEventually:
		return entity.ClEventually
	case ConsistencyLevelCustomized:
		return entity.ClCustomized
	default:
		// ConsistencyLevelDefault (0) or invalid value - default to Bounded
		return entity.ClBounded
	}
}

// MetricType represents the metric type for vector similarity.
type MetricType string

const (
	// L2 represents Euclidean distance (L2 norm).
	// Suitable for dense floating-point vectors.
	L2 MetricType = "L2"

	// IP represents Inner Product similarity.
	// Higher values indicate greater similarity. Suitable for normalized vectors.
	IP MetricType = "IP"

	// COSINE represents Cosine similarity.
	// Measures the cosine of the angle between vectors, ignoring magnitude.
	COSINE MetricType = "COSINE"

	// HAMMING represents Hamming distance for binary vectors.
	// Counts the number of positions where the corresponding bits differ.
	HAMMING MetricType = "HAMMING"

	// JACCARD represents Jaccard distance for binary vectors.
	// Measures dissimilarity between sample sets.
	JACCARD MetricType = "JACCARD"

	// TANIMOTO represents Tanimoto distance for binary vectors.
	// Similar to Jaccard, used for molecular fingerprint comparisons.
	TANIMOTO MetricType = "TANIMOTO"

	// SUBSTRUCTURE represents substructure search for binary vectors.
	// Returns true if A is a subset of B.
	SUBSTRUCTURE MetricType = "SUBSTRUCTURE"

	// SUPERSTRUCTURE represents superstructure search for binary vectors.
	// Returns true if B is a subset of A.
	SUPERSTRUCTURE MetricType = "SUPERSTRUCTURE"

	// BM25 represents BM25 similarity.
	// Used for sparse vectors generated by BM25 function.
	BM25 MetricType = "BM25"
)

// toEntity converts MetricType to the Milvus SDK entity.MetricType type.
func (m MetricType) toEntity() entity.MetricType {
	return entity.MetricType(m)
}
