package tools

import (
	"context"
	"fmt"
	"strings"

	"github.com/cloudwego/eino/components/tool/utils"
)

type skillEvolveInput struct {
	Action      string `json:"action" jsonschema:"description=Evolve action: 'generate', 'evaluate', or 'guide'"`
	SkillName   string `json:"skill_name" jsonschema:"description=The identifier/name of the skill or tool"`
	Description string `json:"description" jsonschema:"description=Detailed intent or capability requirements of the skill"`
	CodeSnippet string `json:"code_snippet,omitempty" jsonschema:"description=Existing or proposed tool implementation for 'evaluate' action"`
}

type skillEvolveOutput struct {
	Success      bool     `json:"success"`
	Action       string   `json:"action"`
	SkillName    string   `json:"skill_name"`
	Score        int      `json:"score,omitempty"` // 0-100 evaluation score
	SafetyPassed bool     `json:"safety_passed"`
	Checklist    []string `json:"checklist,omitempty"`
	Output       string   `json:"output"`
	Error        string   `json:"error,omitempty"`
}

// RegisterSkillEvolveTool registers the `evolve_skill` tool in registry,
// ported and enhanced from PurrCat's evolve/skill subsystem (factory, evaluator, guide_generator).
func RegisterSkillEvolveTool(r *Registry, workspaceRoot string) error {
	t, err := utils.InferTool("evolve_skill",
		"Self-evolution engine for skills and dynamic tools: generates clean Eino/Go tool scaffolds, audits code against safety and robustness checklists, and generates user guidance.",
		func(ctx context.Context, in skillEvolveInput) (skillEvolveOutput, error) {
			action := strings.ToLower(strings.TrimSpace(in.Action))
			name := strings.TrimSpace(in.SkillName)
			if name == "" {
				return skillEvolveOutput{Success: false, Error: "skill_name is required"}, nil
			}

			switch action {
			case "generate":
				scaffold := fmt.Sprintf(`// Package tools - Autogenerated skill: %s
package tools

import (
	"context"
	"strings"

	"github.com/cloudwego/eino/components/tool/utils"
)

type %sInput struct {
	Query string `+"`"+`json:"query" jsonschema:"description=Input parameter for %s"`+"`"+`
}

type %sOutput struct {
	Success bool   `+"`"+`json:"success"`+"`"+`
	Result  string `+"`"+`json:"result"`+"`"+`
	Error   string `+"`"+`json:"error,omitempty"`+"`"+`
}

// Register%sTool adds %s to the registry.
func Register%sTool(r *Registry) error {
	t, err := utils.InferTool("%s",
		"%s",
		func(ctx context.Context, in %sInput) (%sOutput, error) {
			q := strings.TrimSpace(in.Query)
			if q == "" {
				return %sOutput{Success: false, Error: "query required"}, nil
			}
			// TODO: Implement business logic
			return %sOutput{Success: true, Result: "processed: " + q}, nil
		},
	)
	if err != nil {
		return err
	}
	r.AddTool(t)
	return nil
}
`, name, strings.Title(name), name, strings.Title(name), strings.Title(name), name, strings.Title(name), name, in.Description, strings.Title(name), strings.Title(name), strings.Title(name), strings.Title(name))

				return skillEvolveOutput{
					Success:      true,
					Action:       "generate",
					SkillName:    name,
					SafetyPassed: true,
					Output:       scaffold,
				}, nil

			case "evaluate":
				code := in.CodeSnippet
				score := 100
				safetyPassed := true
				var checklist []string

				// 1. Safety audit
				dangerousKeywords := []string{"os.RemoveAll(\"/\"", "exec.Command(\"rm -rf /", "DROP TABLE", "format c:"}
				for _, kw := range dangerousKeywords {
					if strings.Contains(strings.ToLower(code), strings.ToLower(kw)) {
						safetyPassed = false
						score -= 50
						checklist = append(checklist, fmt.Sprintf("❌ 命中高危关键字: %s", kw))
					}
				}
				if safetyPassed {
					checklist = append(checklist, "✅ 未发现硬编码高危破坏性指令")
				}

				// 2. Error handling & context
				if !strings.Contains(code, "context.Context") {
					score -= 15
					checklist = append(checklist, "⚠️ 缺少 context.Context 贯穿取消与超时控制")
				} else {
					checklist = append(checklist, "✅ 包含标准 context.Context 传递")
				}

				if !strings.Contains(code, "jsonschema:") {
					score -= 15
					checklist = append(checklist, "⚠️ 输入结构体缺少 jsonschema 注解，模型无法获知参数语义")
				} else {
					checklist = append(checklist, "✅ 包含清晰的 jsonschema 参数说明")
				}

				if score < 0 {
					score = 0
				}

				return skillEvolveOutput{
					Success:      true,
					Action:       "evaluate",
					SkillName:    name,
					Score:        score,
					SafetyPassed: safetyPassed,
					Checklist:    checklist,
					Output:       fmt.Sprintf("技能 `%s` 综合评分: %d/100 (安全审查: %v)", name, score, safetyPassed),
				}, nil

			case "guide":
				guide := fmt.Sprintf(`# 技能指南：%s

## 描述
%s

## 何时使用 (When to Use)
- 当用户要求执行与 %s 相关的任务时优先调用。
- 处理需要结构化输出的复杂计算或外部查询。

## 何时禁用 (When NOT to Use)
- 简单文本回复或无副作用的纯问答。
- 未提供必需参数时不要凭空猜测调用。
`, name, in.Description, name)

				return skillEvolveOutput{
					Success:      true,
					Action:       "guide",
					SkillName:    name,
					SafetyPassed: true,
					Output:       guide,
				}, nil

			default:
				return skillEvolveOutput{
					Success: false,
					Action:  in.Action,
					Error:   fmt.Sprintf("未知操作 `%s`，有效操作为: generate, evaluate, guide", in.Action),
				}, nil
			}
		},
	)
	if err != nil {
		return err
	}
	r.AddTool(t)
	return nil
}
