/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"context"
	"fmt"
	"log"

	"github.com/cloudwego/eino-ext/components/indexer/milvus2"
	"github.com/cloudwego/eino/components/embedding"
	"github.com/cloudwego/eino/schema"
	"github.com/milvus-io/milvus/client/v2/milvusclient"
)

// This example demonstrates Hybrid Search indexing - creating a collection with
// both Dense vectors (for semantic search) and Sparse vectors (BM25 for keyword search).
//
// The BM25 function tokenizes text and generates term frequency vectors automatically
// on the server side, enabling keyword-based search without client-side sparse embedding.
//
// Prerequisites:
// - Milvus 2.5+ (required for server-side functions)
//
// The collection created here can be used with the retriever hybrid example
// for combined Dense + Sparse (BM25) hybrid search.

func main() {
	ctx := context.Background()
	collectionName := "eino_hybrid_test"
	milvusAddr := "localhost:19530"
	denseField := "vector"
	sparseField := "sparse_vector"

	// Create indexer with BM25 function
	indexer, err := milvus2.NewIndexer(ctx, &milvus2.IndexerConfig{
		ClientConfig: &milvusclient.ClientConfig{
			Address: milvusAddr,
		},
		Collection: collectionName,
		Vector: &milvus2.VectorConfig{
			VectorField: denseField,
			Dimension:   128, // Dense vector dimension
		},

		// BM25 requires analyzer on content field.
		// Analyzer options (built-in):
		// - {"type": "standard"} - general-purpose, tokenization + lowercase
		// - {"type": "english"}  - English with stopwords support
		// - {"type": "chinese"}  - Chinese with Jieba segmentation
		// - Custom: {"tokenizer": "...", "filter": [...]}
		// See: https://milvus.io/docs/analyzer-overview.md
		FieldParams: map[string]map[string]string{
			"content": {
				"enable_analyzer": "true",
				"analyzer_params": `{"type": "standard"}`, // Use {"type": "chinese"} for Chinese text
			},
		},
		// Functions: Auto-generated for BM25 when Sparse is set
		Sparse: &milvus2.SparseVectorConfig{
			VectorField: sparseField,
			MetricType:  milvus2.BM25,
			Method:      milvus2.SparseMethodAuto,
		},
		Embedding: &mockEmbedding{dim: 128},
	})
	if err != nil {
		log.Fatalf("Failed to create indexer: %v", err)
	}

	// Store documents - only dense vectors needed, sparse is generated by Milvus
	ids, err := indexer.Store(ctx, []*schema.Document{
		{ID: "1", Content: "Milvus is a highly scalable vector database for AI applications."},
		{ID: "2", Content: "Eino framework simplifies building AI-powered applications in Go."},
		{ID: "3", Content: "Vector search enables semantic similarity matching."},
	})
	if err != nil {
		log.Fatalf("Failed to store: %v", err)
	}

	fmt.Printf("Stored %d documents: %v\n", len(ids), ids)
	fmt.Println("Use the retriever hybrid example to search this collection with BM25.")
}

// mockEmbedding for demo purposes
type mockEmbedding struct{ dim int }

func (m *mockEmbedding) EmbedStrings(ctx context.Context, texts []string, opts ...embedding.Option) ([][]float64, error) {
	vecs := make([][]float64, len(texts))
	for i := range texts {
		vecs[i] = make([]float64, m.dim)
		vecs[i][0] = 0.1
	}
	return vecs, nil
}
